# -*- coding: utf-8 -*-
"""BI Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgDmfIglQWGqnvjbJ8jVfZfi195Z5Qv-

# CSV Dataset Cleaning
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

file_name = 'costco_store.csv'
df = pd.read_csv(file_name)

df.head()

# Count the number of unique values in the 'Address' column
unique_count = df['address_1'].nunique()

print(f"Number of unique addresses: {unique_count}")

print(df.info())  # Data types and non-null counts
print(df.head())  # First few rows
print(df.describe())  # Summary statistics for numerical columns

#Check for missing data in each column:
print(df.isnull().sum())

# Relevant columns from your dataset
columns_to_check = ['loc_name', 'loc_number']  # Replace 'displayName' and 'identifier'
reference_column = 'tid'  # Replace 'stlocID'

# Initialize a flag to detect any mismatches
has_mismatch = False

# Loop through columns to check redundancy with the reference column
for col in columns_to_check:
    if col in df.columns:  # Ensure the column exists in the dataset
        comparison_result = df[reference_column] == df[col]  # Element-wise comparison
        if not comparison_result.all():  # Check if all values are True
            has_mismatch = True
            print(f"Mismatch found in column: {col}")
            print(f"Mismatched rows:\n{df[~comparison_result]}")  # Print mismatched rows
        else:
            print(f"Column '{col}' is fully redundant with '{reference_column}'.")
    else:
        print(f"Column '{col}' does not exist in the dataset.")

# Final result
if has_mismatch:
    print("Some columns are not redundant with the reference column.")
else:
    print("All checked columns are fully redundant with the reference column.")

df = df.drop(columns=['loc_name', 'loc_number'])

print(df.info())
print(df.head())

#Check for Missing Values:
print(df.isnull().sum())

df

#Remove extra spaces, normalize casing, etc.:
string_columns = ['address_1', 'city', 'state', 'country']  # Example
for col in string_columns:
    df[col] = df[col].str.strip().str.title()

df['opening_date'] = pd.to_datetime(df['opening_date'], errors='coerce')

#Ensure numeric columns like latitude and longitude are floats:
df[['latitude', 'longitude']] = df[['latitude', 'longitude']].astype(float)

#Remove Duplicates
df = df.drop_duplicates(subset='tid')

#Verify that tid is still unique after dropping columns:
if df['tid'].is_unique:
    print("All 'tid' values are unique.")
else:
    print("Duplicate 'tid' values found!")

print(df.describe())

# Drop rows with missing opening_date
df.dropna(subset=['opening_date'], inplace=True)

# Drop the RunID column
df.drop(columns=['RunID'], inplace=True)

# Check for duplicates and remove them
df.drop_duplicates(inplace=True)

df

# Check data types
print(df.dtypes)

# Check for missing values in the entire dataset
missing_values = df.isnull().sum()
print(missing_values)

# If no missing values exist, it should output 0 for all columns
if missing_values.sum() == 0:
    print("Dataset is clean (no missing values).")
else:
    print("Dataset still has missing values.")

# Check for duplicates
duplicates = df.duplicated().sum()
if duplicates == 0:
    print("No duplicates found.")
else:
    print(f"There are {duplicates} duplicate rows.")

# Check the remaining columns in the dataset
print(df.columns)

# Get a summary of the dataset
print(df.describe())

df

# List of columns to drop
columns_to_drop = ['contact', 'RunDate', 'phone', 'postal_code', 'InsertUpdateTime', 'latitude', 'longitude', 'RunID']

# Drop the columns
df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

df

df.to_csv('Costco.csv', index=False)

df.to_csv('costco_store.csv', index=False)

from google.colab import files
files.download('costco_store.csv')

print(df.columns)

df= df.rename(columns={'address_1': 'Address'})

df['Address'] = df['Address'].str.strip()  # Remove leading/trailing spaces
df['Address'] = df['Address'].str.replace(r'\s+', ' ', regex=True)  # Replace multiple spaces with a single space

df['Address'] = df['Address'].str.upper()  # Convert to uppercase

abbreviations = {
    'St': 'Street',
    'Ave': 'Avenue',
    'Rd': 'Road',
    'Blvd': 'Boulevard',
    'Dr': 'Drive'
}
df['Address'] = df['Address'].replace(abbreviations, regex=True)

df['Address'] = df['Address'].str.replace('[,\.]', '', regex=True)  # Remove commas and periods

df.head()

df['country'] = df['country'].str.upper()  # Convert to uppercase
df['state'] = df['state'].str.upper()  # Convert to uppercase
df['city'] = df['city'].str.upper()  # Convert to uppercase

df.head()



df.to_csv('costco_store.csv', index=False)

from google.colab import files
files.download('costco_store.csv')

"""# JSON Dataset Cleaning"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

file_name = "costco_warehouses.json"
data = pd.read_json(file_name)

data.head()

print(data[['stlocID', 'displayName', 'identifier']].head())
print(data['stlocID'].equals(data['displayName']))
print(data['stlocID'].equals(data['identifier']))

columns_to_check = ['displayName', 'identifier']
reference_column = 'stlocID'

# Initialize a flag to detect any mismatches
has_mismatch = False

# Loop through columns to check redundancy with the reference column
for col in columns_to_check:
    comparison_result = data[reference_column] == data[col]  # Element-wise comparison
    if not comparison_result.all():  # Check if all values are True
        has_mismatch = True
        print(f"Mismatch found in column: {col}")
        print(f"Mismatched rows:\n{df[~comparison_result]}")  # Print mismatched rows
    else:
        print(f"Column '{col}' is fully redundant with '{reference_column}'.")

# Final result
if has_mismatch:
    print("Some columns are not redundant with the reference column.")
else:
    print("All checked columns are fully redundant with the reference column.")

data = data.drop(columns=['displayName', 'identifier'])

data.head()

data = data.drop(columns=['phone', 'fax'])

data.head()

print(data.columns)

data=data.drop(columns=['tiresDepartmentPhone'])

data.head()

unique_values = data['parentGeoNodeID'].unique()
print (unique_values)

unique_values = data['closeDate'].unique()
print (unique_values)

count = data['closeDate'].value_counts().get('Oct 21, 1993', 0)
print(f"The value 'Oct 21, 1993' is repeated {count} times in the 'closeDate' column.")

data=data.drop(columns=['closeDate'])

data=data.drop(columns=['parentGeoNodeID'])

data.head()

data=data.drop(columns=['manager'])

data=data.drop(columns=['latitude', 'longitude'])

data.head()

unique_values = data['active'].unique()
print (unique_values)

unique_values = data['languageID'].unique()
print (unique_values)

data=data.drop(columns=['active', 'languageID'])

print(data.columns)

duplicate_values = data[data['stlocID'].duplicated()]
print("Duplicate rows based on 'stlocID':")
print(duplicate_values)

null_counts = data.isnull().sum()

print("Number of null values in each column:")
print(null_counts)

data['regularPrices'] = data['gasPrices'].apply(lambda x: x.get('regular') if isinstance(x, dict) else None)

# Find unique values in 'regularPrices'
unique_values = data['regularPrices'].unique()
print(unique_values)

value_counts = data['regularPrices'].value_counts()

# Print the counts
print(value_counts)

value_counts = data['regularPrices'].value_counts(dropna=False)
print(value_counts)

data['regularPrices'] = pd.to_numeric(data['regularPrices'], errors='coerce')

# Calculate the mean and median
mean_price = data['regularPrices'].mean()
median_price = data['regularPrices'].median()

# Print the results
print(f"Mean Regular Gas Price: {mean_price}")
print(f"Median Regular Gas Price: {median_price}")

# Function to remove the 'phone' key from each dictionary in the list
def remove_phone_key(departments):
    if isinstance(departments, list):
        return [{key: value for key, value in dept.items() if key != 'phone'} for dept in departments]
    return departments  # Return unchanged if not a list

# Apply the function to the 'specialtyDepartments' column
data['specialtyDepartments'] = data['specialtyDepartments'].apply(remove_phone_key)

# Display the updated column
print(data['specialtyDepartments'].head())

data.head()

data.drop(columns=['gasPrices'])

print(data.columns)

nested_columns = ['warehouseHours', 'pharmacyHours', 'upcomingHolidays', 'gasStationHours', 'tireCenterHours', 'coreServices', 'specialtyDepartments']
for column in nested_columns:
    if isinstance(data[column].iloc[0], dict):
        print(f"Columns inside {column}:")
        # Assuming the first entry is a dictionary, get the keys as column names
        print(data[column].iloc[0].keys())
    elif isinstance(data[column].iloc[0], list):
        print(f"Columns inside {column}:")
        # If it's a list, print the length of the first list
        print(len(data[column].iloc[0]))
    print("\n")

data=data.drop(columns=['regularPrices'])

print(data.columns)

def remove_phone_from_core_services(core_services):
    for service in core_services:
        if 'phone' in service:
            del service['phone']
    return core_services

# Apply the function to the 'coreServices' column
data['coreServices'] = data['coreServices'].apply(remove_phone_from_core_services)

# Check the result
print(data['coreServices'].head())

def check_name_localized_name(core_services):
    mismatched_services = []
    for service in core_services:
        if service['name'] != service['localizedName']:
            mismatched_services.append(service)
    return mismatched_services

# Apply the function to the 'coreServices' column
data['name_localized_name_mismatch'] = data['coreServices'].apply(check_name_localized_name)

# Check if there are any mismatches and print them
mismatched_rows = data[data['name_localized_name_mismatch'].str.len() > 0]

if not mismatched_rows.empty:
    print("Warning: There are rows where 'name' and 'localizedName' do not match!")
    print("Mismatched rows:")
    print(mismatched_rows[['coreServices', 'name_localized_name_mismatch']])
else:
    print("All 'name' and 'localizedName' values are the same.")

def remove_localized_name(core_services):
    for service in core_services:
        if 'localizedName' in service:
            del service['localizedName']
    return core_services

# Apply the function to the 'coreServices' column
data['coreServices'] = data['coreServices'].apply(remove_localized_name)

# Check the result
print(data[['coreServices']].head())

data['name_localized_name_mismatch'] = data['specialtyDepartments'].apply(check_name_localized_name)

# Check if there are any mismatches and print them
mismatched_rows = data[data['name_localized_name_mismatch'].str.len() > 0]

if not mismatched_rows.empty:
    print("Warning: There are rows where 'name' and 'localizedName' do not match!")
    print("Mismatched rows:")
    print(mismatched_rows[['coreServices', 'name_localized_name_mismatch']])
else:
    print("All 'name' and 'localizedName' values are the same.")

data['specialtyDepartments'] = data['specialtyDepartments'].apply(remove_localized_name)

print(data[['specialtyDepartments']].head())

# Function to extract the holiday name or any relevant field from dictionaries
def extract_holiday_value(holidays):
    # Extract values (e.g., 'name' or any other relevant field)
    return [holiday.get('name', None) for holiday in holidays] if isinstance(holidays, list) else [holidays]

# Flatten the lists and extract holiday names (or other field you want) from the dictionary
flattened_holidays = [item for sublist in data['upcomingHolidays'] for item in extract_holiday_value(sublist)]

# Get unique values
unique_holidays = set(flattened_holidays)

# Print the unique holidays
print(unique_holidays)

data=data.drop(columns=['upcomingHolidays'])

print(data.columns)

data.head()

if (data['city'].str.lower() == data['locationName'].str.lower()).all():
    print("The 'city' and 'locationName' columns have the same values in all rows.")
else:
    print("There are rows where 'city' and 'locationName' do not match.")
    # Optional: Display rows where the values are different
    mismatched_rows = data[data['city'] != data['locationName']]
    print("Mismatched rows:")
    print(mismatched_rows[['city', 'locationName']])

data=data.drop(columns=['locationName'])

data['distance'] = data['distance'].round(2)
print(data[['distance']].head())

print(data.dtypes)

boolean_columns = ['hasGasDepartment', 'hasTiresDepartment', 'hasFoodDepartment',
                   'hasHearingDepartment', 'hasPharmacyDepartment', 'hasOpticalDepartment',
                   'hasBusinessDepartment', 'hasPhotoCenterDepartment', 'isShipToWarehouse',
                   'isWarehousePickup', 'enableShipToHome', 'isBusinessWarehouse']

# Check unique values for all boolean columns
for col in boolean_columns:
    print(f"Unique values in '{col}': {data[col].unique()}")

# Convert 'openDate' column to datetime type
data['openDate'] = pd.to_datetime(data['openDate'], errors='coerce')

# Check the data type of 'openDate' to confirm the change
print(data['openDate'].dtypes)

print(data[['openDate']].head())

# Convert 'openDate' column to datetime type
data['openDate'] = pd.to_datetime(data['openDate'], errors='coerce')

# Convert datetime objects to strings in 'openDate'
data['openDate'] = data['openDate'].dt.strftime('%Y-%m-%d')  # Format as YYYY-MM-DD

# Convert the DataFrame to a dictionary
data_dict = data.to_dict(orient='records')

# Save the data to a JSON file
import json
with open("modified_data.json", "w") as file:
    json.dump(data_dict, file, indent=4)

data=data.drop(columns=['gasPrices'])

print(data.columns)

data=data.drop(columns=['name_localized_name_mismatch'])

data.head()

def transform_to_simple_list(data):
    day_map = {
        "Mon-Fri.": "M-F",
        "Sat.": "SAT",
        "Sun.": "SUN"
    }
    transformed_list = []
    for entry in data:
        # Map title to the desired format
        day = day_map.get(entry["title"], entry["title"])
        # Replace time formatting
        time = entry["time"].replace(" ", "") if entry["code"] == "open" else "CLOSED"
        # Combine day and time
        transformed_list.append(f"{day} {time}")
    return transformed_list

# Apply the transformation to the 'gasStationHours' column
data["gasStationHours"] = data["gasStationHours"].apply(transform_to_simple_list)
data["tireCenterHours"] = data["tireCenterHours"].apply(transform_to_simple_list)

data.head()

data.columns

data=data.drop(columns=['zipCode'])

# Convert the DataFrame to a dictionary
data_dict = data.to_dict(orient='records')

# Save the data to a JSON file
with open("last_modified_data.json", "w") as file:
    json.dump(data_dict, file, indent=4)
    files.download("last_modified_data.json")

data= data.rename(columns={'address1': 'Address'})

data.columns

data['Address'] = data['Address'].str.strip()  # Remove leading/trailing spaces
data['Address'] = data['Address'].str.replace(r'\s+', ' ', regex=True)  # Replace multiple spaces with a single space

data['Address'] = data['Address'].str.upper()  # Convert to uppercase

abbreviations = {
    'St': 'Street',
    'Ave': 'Avenue',
    'Rd': 'Road',
    'Blvd': 'Boulevard',
    'Dr': 'Drive'
}
data['Address'] = data['Address'].replace(abbreviations, regex=True)

data['Address'] = data['Address'].str.replace('[,\.]', '', regex=True)  # Remove commas and periods

data.head()

# Count the number of unique values in the 'Address' column
unique_count = data['Address'].nunique()

print(f"Number of unique addresses: {unique_count}")

data.head()

output_file = "pretty_transformed_data.csv"
data.to_csv(output_file, index=False)

files.download(output_file)

"""# Merging"""

merged_data = pd.merge(df, data, on=['Address', 'city','state','country'], how='inner')

merged_data.head()

merged_data.columns

# Merging the dataset
merged_data = pd.merge(df, data, on=['Address', 'city', 'state', 'country'], how='inner')

# Saving the merged dataset to a CSV file
merged_data.to_csv('merged_dataset.csv', index=False)

print("The merged dataset has been saved as 'merged_dataset.csv'. You can download it now.")
# Provide a download prompt
files.download('merged_dataset.csv')

# Merging the dataset
merged_data = pd.merge(df, data, on=['Address', 'city', 'state', 'country'], how='inner')

# Saving the merged dataset to an Excel file
merged_data.to_excel('merged_dataset.xlsx', index=False)

print("The merged dataset has been saved as 'merged_dataset.xlsx'. You can download it now.")

# Provide a download prompt
files.download('merged_dataset.xlsx')

# Dropping the specified columns
columns_to_drop = ['opening_date', 'loc_type', 'parentGeoNodeID', 'tid']
data_cleaned = data.drop(columns=columns_to_drop, errors='ignore')

# Save the cleaned dataset back to a file (optional)
data_cleaned.to_excel('cleaned_dataset.xlsx', index=False)

print("Specified columns dropped. Cleaned dataset saved as 'cleaned_dataset.xlsx'.")

# Save the cleaned dataset as a CSV file
data_cleaned.to_csv('cleaned_dataset.csv', index=False)

# Save the cleaned dataset as an Excel file
data_cleaned.to_excel('cleaned_dataset.xlsx', index=False)

print("Cleaned dataset saved as 'cleaned_dataset.csv' and 'cleaned_dataset.xlsx'.")

from google.colab import files

# Download the CSV file
files.download('cleaned_dataset.csv')

# Download the Excel file
files.download('cleaned_dataset.xlsx')

# Reset stlocID to be sequential starting from 1
data['stlocID'] = range(1, len(data) + 1)

data.head()

data['locationID'] = range(1000, 1000 + len(data))
data['departmentsID'] = range(2000, 2000 + len(data))
data['Hours_of_opID'] = range(3000, 3000 + len(data))
data['ServicesID'] = range(4000, 4000 + len(data))

data = data.drop(columns=['departments'])

data.head()

# Save the dataset as a CSV file
data.to_csv('cleaned_dataset.csv', index=False)

# Save the dataset as an Excel file
data.to_excel('cleaned_dataset.xlsx', index=False)

# Provide files for download
files.download('cleaned_dataset.csv')
files.download('cleaned_dataset.xlsx')

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("cleaned_dataset (1).csv")

df['CapabilityID'] = range(5000, 5000 + len(df))

df.head()

# Save the updated DataFrame to a CSV file
csv_output_file = "updated_cleaned_dataset.csv"
df.to_csv(csv_output_file, index=False)
print(f"CSV file saved as {csv_output_file}")

# Save the updated DataFrame to an Excel file
excel_output_file = "updated_cleaned_dataset.xlsx"
df.to_excel(excel_output_file, index=False, engine='openpyxl')
print(f"Excel file saved as {excel_output_file}")

# Download the files to your local machine
files.download(csv_output_file)
files.download(excel_output_file)



